#ifndef HANKAKUKANA_H
#define HANKAKUKANA_H

/* "AイCテL since 12 thousand years ago" == "A" HK_I "C" HK_TE "L since 12 thousand years ago" */

#define HK_KUTEN "\xA1"
#define HK_KAGI_BEG "\xA2"
#define HK_KAGI_END "\xA3"
#define HK_TOUTEN "\xA4"
#define HK_TEN "\xA5"
#define HK_WO "\xA6"
#define HK_A_SMALL "\xA7"
#define HK_I_SMALL "\xA8"
#define HK_U_SMALL "\xA9"
#define HK_E_SMALL "\xAA"
#define HK_O_SMALL "\xAB"
#define HK_YA_SMALL "\xAC"
#define HK_YU_SMALL "\xAD"
#define HK_YO_SMALL "\xAE"
#define HK_TU_SMALL "\xAF"
#define HK_ONBIKI "\xB0" /* ソフトウェア工学のテストで出た */
#define HK_A "\xB1"
#define HK_I "\xB2"
#define HK_U "\xB3"
#define HK_E "\xB4"
#define HK_O "\xB5"
#define HK_KA "\xB6"
#define HK_KI "\xB7"
#define HK_KU "\xB8"
#define HK_KE "\xB9"
#define HK_KO "\xBA"
#define HK_SA "\xBB"
#define HK_SI "\xBC"
#define HK_SU "\xBD"
#define HK_SE "\xBE"
#define HK_SO "\xBF"
#define HK_TA "\xC0"
#define HK_TI "\xC1"
#define HK_TU "\xC2"
#define HK_TE "\xC3"
#define HK_TO "\xC4"
#define HK_NA "\xC5"
#define HK_NI "\xC6"
#define HK_NU "\xC7"
#define HK_NE "\xC8"
#define HK_NO "\xC9"
#define HK_HA "\xCA"
#define HK_HI "\xCB"
#define HK_HU "\xCC"
#define HK_HE "\xCD"
#define HK_HO "\xCE"
#define HK_MA "\xCF"
#define HK_MI "\xD0"
#define HK_MU "\xD1"
#define HK_ME "\xD2"
#define HK_MO "\xD3"
#define HK_YA "\xD4"
#define HK_YU "\xD5"
#define HK_YO "\xD6"
#define HK_RA "\xD7"
#define HK_RI "\xD8"
#define HK_RU "\xD9"
#define HK_RE "\xDA"
#define HK_RO "\xDB"
#define HK_WA "\xDC"
#define HK_N "\xDD"
#define HK_DAKUTEN "\xDE"
#define HK_HANDAKUTEN "\xDF"

#endif
